-- QUERY 1: Delinquency rate by state
SELECT
    PROPERTY_STATE,
    COUNT(*) AS TOTAL_LOANS,
    SUM(CASE WHEN DELINQUENCY_BUCKET = '90+ day' THEN 1 ELSE 0 END) AS DELINQUENT_90,
    SUM(CASE WHEN DELINQUENCY_BUCKET = '60-day'  THEN 1 ELSE 0 END) AS DELINQUENT_60,
    SUM(CASE WHEN DELINQUENCY_BUCKET = '30-day'  THEN 1 ELSE 0 END) AS DELINQUENT_30,
    ROUND(DELINQUENT_90 / NULLIF(TOTAL_LOANS, 0) * 100, 2) AS DELINQUENCY_RATE_PCT,
    ROUND(AVG(CREDIT_SCORE), 0) AS AVG_FICO,
    ROUND(AVG(ORIGINAL_LTV), 1) AS AVG_LTV,
    ROUND(AVG(ORIGINAL_DTI), 1) AS AVG_DTI
FROM MORTGAGE_DB.ANALYTICS.FACT_LOAN_MONTHLY
GROUP BY PROPERTY_STATE
ORDER BY DELINQUENCY_RATE_PCT DESC;

-- QUERY 2: Monthly delinquency trend
SELECT
    MONTHLY_REPORTING_PERIOD,
    COUNT(*) AS TOTAL_LOANS,
    SUM(CASE WHEN DELINQUENCY_BUCKET != 'Current' THEN 1 ELSE 0 END) AS TOTAL_DELINQUENT,
    SUM(CASE WHEN DELINQUENCY_BUCKET = '30-day'   THEN 1 ELSE 0 END) AS BUCKET_30,
    SUM(CASE WHEN DELINQUENCY_BUCKET = '60-day'   THEN 1 ELSE 0 END) AS BUCKET_60,
    SUM(CASE WHEN DELINQUENCY_BUCKET = '90+ day'  THEN 1 ELSE 0 END) AS BUCKET_90,
    ROUND(TOTAL_DELINQUENT / NULLIF(TOTAL_LOANS, 0) * 100, 2) AS OVERALL_DELINQUENCY_RATE
FROM MORTGAGE_DB.ANALYTICS.FACT_LOAN_MONTHLY
GROUP BY MONTHLY_REPORTING_PERIOD
ORDER BY MONTHLY_REPORTING_PERIOD;

-- QUERY 3: Risk tier breakdown
SELECT
    RISK_TIER,
    COUNT(*) AS LOAN_COUNT,
    ROUND(AVG(CREDIT_SCORE), 0) AS AVG_FICO,
    ROUND(AVG(ORIGINAL_DTI), 1) AS AVG_DTI,
    ROUND(AVG(ORIGINAL_LTV), 1) AS AVG_LTV,
    SUM(CASE WHEN DEFAULT_FLAG = 1 THEN 1 ELSE 0 END) AS DEFAULTS,
    ROUND(DEFAULTS / NULLIF(LOAN_COUNT, 0) * 100, 2) AS DEFAULT_RATE_PCT
FROM MORTGAGE_DB.ANALYTICS.FACT_LOAN_MONTHLY
GROUP BY RISK_TIER
ORDER BY DEFAULT_RATE_PCT DESC;

-- QUERY 4: Portfolio summary KPIs
SELECT
    COUNT(DISTINCT LOAN_SEQUENCE_NUMBER) AS TOTAL_UNIQUE_LOANS,
    SUM(ORIGINAL_UPB) AS TOTAL_PORTFOLIO_UPB,
    ROUND(AVG(CREDIT_SCORE), 0) AS AVG_FICO_SCORE,
    ROUND(AVG(ORIGINAL_LTV), 1) AS AVG_LTV,
    ROUND(AVG(ORIGINAL_DTI), 1) AS AVG_DTI,
    SUM(CASE WHEN DELINQUENCY_BUCKET != 'Current' THEN 1 ELSE 0 END) AS TOTAL_DELINQUENT,
    ROUND(TOTAL_DELINQUENT / NULLIF(COUNT(*), 0) * 100, 2) AS OVERALL_DELINQUENCY_RATE
FROM MORTGAGE_DB.ANALYTICS.FACT_LOAN_MONTHLY
WHERE MONTHLY_REPORTING_PERIOD = (
    SELECT MAX(MONTHLY_REPORTING_PERIOD)
    FROM MORTGAGE_DB.ANALYTICS.FACT_LOAN_MONTHLY
);