-- Run this once in Snowsight to set up your database structure

CREATE DATABASE IF NOT EXISTS MORTGAGE_DB;
USE DATABASE MORTGAGE_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS MORTGAGE_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE MORTGAGE_WH;

CREATE OR REPLACE TABLE MORTGAGE_DB.RAW.ORIGINATION (
    CREDIT_SCORE               NUMBER,
    FIRST_PAYMENT_DATE         VARCHAR(10),
    FIRST_TIME_HOMEBUYER_FLAG  VARCHAR(1),
    MATURITY_DATE              VARCHAR(10),
    MSA                        VARCHAR(10),
    MI_PERCENTAGE              NUMBER,
    NUMBER_OF_UNITS            NUMBER,
    OCCUPANCY_STATUS           VARCHAR(1),
    ORIGINAL_CLTV              NUMBER,
    ORIGINAL_DTI               NUMBER,
    ORIGINAL_UPB               NUMBER,
    ORIGINAL_LTV               NUMBER,
    ORIGINAL_INTEREST_RATE     FLOAT,
    CHANNEL                    VARCHAR(1),
    PREPAYMENT_PENALTY_FLAG    VARCHAR(1),
    PRODUCT_TYPE               VARCHAR(5),
    PROPERTY_STATE             VARCHAR(2),
    PROPERTY_TYPE              VARCHAR(2),
    POSTAL_CODE                VARCHAR(5),
    LOAN_SEQUENCE_NUMBER       VARCHAR(20),
    LOAN_PURPOSE               VARCHAR(1),
    ORIGINAL_LOAN_TERM         NUMBER,
    NUMBER_OF_BORROWERS        NUMBER,
    SELLER_NAME                VARCHAR(100),
    SERVICER_NAME              VARCHAR(100),
    SUPER_CONFORMING_FLAG      VARCHAR(1),
    LOAD_DATE                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE MORTGAGE_DB.RAW.PERFORMANCE (
    LOAN_SEQUENCE_NUMBER                   VARCHAR(20),
    MONTHLY_REPORTING_PERIOD               VARCHAR(10),
    CURRENT_ACTUAL_UPB                     NUMBER,
    CURRENT_LOAN_DELINQUENCY_STATUS        VARCHAR(3),
    LOAN_AGE                               NUMBER,
    REMAINING_MONTHS_TO_LEGAL_MATURITY     NUMBER,
    REPURCHASE_FLAG                        VARCHAR(1),
    MODIFICATION_FLAG                      VARCHAR(1),
    ZERO_BALANCE_CODE                      VARCHAR(2),
    ZERO_BALANCE_EFFECTIVE_DATE            VARCHAR(10),
    CURRENT_INTEREST_RATE                  FLOAT,
    LOAD_DATE                              TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE MORTGAGE_DB.ANALYTICS.FACT_LOAN_MONTHLY (
    LOAN_SEQUENCE_NUMBER        VARCHAR(20),
    MONTHLY_REPORTING_PERIOD    DATE,
    PROPERTY_STATE              VARCHAR(2),
    CREDIT_SCORE                NUMBER,
    ORIGINAL_LTV                NUMBER,
    ORIGINAL_DTI                NUMBER,
    ORIGINAL_INTEREST_RATE      FLOAT,
    ORIGINAL_UPB                NUMBER,
    LOAN_AGE                    NUMBER,
    CURRENT_ACTUAL_UPB          NUMBER,
    DELINQUENCY_STATUS_RAW      VARCHAR(3),
    DELINQUENCY_BUCKET          VARCHAR(20),
    RISK_TIER                   VARCHAR(20),
    DEFAULT_FLAG                NUMBER,
    LOAN_PURPOSE                VARCHAR(1),
    SELLER_NAME                 VARCHAR(100)
);

CREATE OR REPLACE TABLE MORTGAGE_DB.ANALYTICS.AGG_STATE_DELINQUENCY (
    PROPERTY_STATE              VARCHAR(2),
    REPORTING_PERIOD            DATE,
    TOTAL_LOANS                 NUMBER,
    CURRENT_LOANS               NUMBER,
    DELINQUENT_30               NUMBER,
    DELINQUENT_60               NUMBER,
    DELINQUENT_90_PLUS          NUMBER,
    FORECLOSURE_COUNT           NUMBER,
    DELINQUENCY_RATE_PCT        FLOAT,
    AVG_CREDIT_SCORE            FLOAT,
    AVG_LTV                     FLOAT,
    AVG_DTI                     FLOAT
);

SELECT 'Setup complete!' AS STATUS;